force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Accounting Unit</label>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TA_JE_SetDefaultValues.cls
public without sharing class TA_JE_SetDefaultValues implements TriggerAction.BeforeInsert {

    // From original context query - all GAUs by gl code
    private static Map<String, npsp__General_Accounting_Unit__c> mapGlCodeToGau;

    /*****************************************************
     * Called by metadata trigger handler
     * Manage from sObject Trigger Settings mdt: Journal Entry
     ******************************************************/
    
    public void beforeInsert(
        List<Journal_Entry__c> newList
    ) {
        mapGlCodeToGau = TA_JE_QueriesBI.getInstance().mapGlCodeToGau;
        for (Journal_Entry__c je : newList) {
            if (mapGlCodeToGau.containsKey(je.GL_Code__c)) {
                je.General_Accounting_Unit__c = mapGlCodeToGau.get(je.GL_Code__c).Id;
            }
        }
    }

}