force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_GL_Account__mdt/Global_GL_Account__mdt.object-meta.xml
<CustomObject>
    <description>Stores GL codes and names for payment and receivables accounts</description>
    <label>Global GL Account</label>
    <pluralLabel>Global GL Accounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_GL_Account__mdt/fields/GL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Name__c</fullName>
    <description>The GL account name as it should appear in the ledger</description>
    <inlineHelpText>The GL account name as it should appear in the ledger</inlineHelpText>
    <label>GL Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_GL_Account__mdt/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_GL_Account__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Receivables</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting Period</label>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The absolute value of the debit/credit amount</description>
    <inlineHelpText>The absolute value of the debit/credit amount</inlineHelpText>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The effective date of the journal entry</description>
    <inlineHelpText>The effective date of the journal entry</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Accounting Unit</label>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/GL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Name__c</fullName>
    <label>GL Account Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Posting_Status__c.field-meta.xml
<CustomField>
    <fullName>Posting_Status__c</fullName>
    <defaultValue>&quot;Entered&quot;</defaultValue>
    <description>The posting status to the general ledger</description>
    <inlineHelpText>The posting status to the general ledger</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/fsl_ManualAdjustmentController.cls
public with sharing class fsl_ManualAdjustmentController {

    // Cache map of gl accounts
    private static Map<Id, GlAccountWrapper> mapGlAccountWrappers;

    /****************************************************
     * Return list of objects with gl ids, names and codes
     ****************************************************/
    
    @AuraEnabled(cacheable=true)
    public static List<GlAccountWrapper> getGlAccounts() {
        try {
            if (mapGlAccountWrappers == null) {
                mapGlAccountWrappers = new Map<Id, GlAccountWrapper>();
                Set<String> setLabels = new Set<String>();
                // Add all gaus
                List<npsp__General_Accounting_Unit__c> lstGaus = [
                    SELECT Id, Name, GL_Code__c 
                      FROM npsp__General_Accounting_Unit__c 
                     WHERE GL_Code__c != null
                     ORDER BY Name ASC
                     LIMIT 10000
                ];
                for (npsp__General_Accounting_Unit__c gau : lstGaus) {
                    String label = gau.Name + ' (' + gau.GL_Code__c + ')';
                    if (!setLabels.contains(label)) {
                        GlAccountWrapper wrapper = new GlAccountWrapper();
                        wrapper.id = gau.Id;
                        wrapper.name = gau.Name;
                        wrapper.code = gau.GL_Code__c;
                        wrapper.label = label;
                        wrapper.isGau = true;
                        mapGlAccountWrappers.put(wrapper.Id, wrapper);
                        setLabels.add(label);
                    }
                }
                // Add all global accounts
                for (Global_GL_Account__mdt ggl : Global_GL_Account__mdt.getAll().values()) {
                    String label = ggl.GL_Account_Name__c + ' (' + ggl.GL_Code__c + ')';
                    if (!setLabels.contains(label)) {
                        GlAccountWrapper wrapper = new GlAccountWrapper();
                        wrapper.id = ggl.Id;
                        wrapper.name = ggl.GL_Account_Name__c;
                        wrapper.code = ggl.GL_Code__c;
                        wrapper.label = label;
                        wrapper.isGau = false;
                        mapGlAccountWrappers.put(wrapper.Id, wrapper);
                        setLabels.add(label);
                    }
                }
            }

            return mapGlAccountWrappers.values();

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String createAdjustmentJournalEntries(
        String accountingPeriodId, 
        Date jeDate, 
        Decimal jeAmount, 
        String jeDebitAccountId, 
        String jeCreditAccountId, 
        String jeNotes
    ) {
        try {
            List<Journal_Entry__c> lstJEsToInsert = new List<Journal_Entry__c>();

            // Load account map
            getGlAccounts();

            System.debug(':::: accountingPeriodId: ' + accountingPeriodId);

            // Debit entry
            Journal_Entry__c jeDebit = new Journal_Entry__c();
            GlAccountWrapper debitWrapper = mapGlAccountWrappers.get(jeDebitAccountId);
            jeDebit.Accounting_Period__c = accountingPeriodId;
            jeDebit.Manual_Adjustment__c = true;
            jeDebit.Type__c = 'Debit';
            jeDebit.Amount__c = jeAmount;
            jeDebit.Date__c = jeDate;
            jeDebit.GL_Account_Name__c = debitWrapper.name;
            jeDebit.GL_Code__c = debitWrapper.code;
            jeDebit.Posting_Status__c = 'Entered';
            jeDebit.General_Accounting_Unit__c = debitWrapper.isGau ? debitWrapper.id : null;
            jeDebit.Notes__c = jeNotes;
            lstJEsToInsert.add(jeDebit);

            // Credit entry
            Journal_Entry__c jeCredit = new Journal_Entry__c();
            GlAccountWrapper creditWrapper = mapGlAccountWrappers.get(jeCreditAccountId);
            jeCredit.Accounting_Period__c = accountingPeriodId;
            jeCredit.Manual_Adjustment__c = true;
            jeCredit.Type__c = 'Credit';
            jeCredit.Amount__c = jeAmount;
            jeCredit.Date__c = jeDate;
            jeCredit.GL_Account_Name__c = creditWrapper.name;
            jeCredit.GL_Code__c = creditWrapper.code;
            jeCredit.Posting_Status__c = 'Entered';
            jeCredit.General_Accounting_Unit__c = creditWrapper.isGau ? creditWrapper.id : null;
            jeCredit.Notes__c = jeNotes;
            lstJEsToInsert.add(jeCredit);

            insert lstJEsToInsert;

            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /****************************************************
     * Wrapper to unify gaus and global accounts
     ****************************************************/

    public class GlAccountWrapper {
        @AuraEnabled
        public Id id {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String code {get;set;}
        @AuraEnabled
        public String label {get;set;}
        @AuraEnabled
        public Boolean isGau {get;set;}
    }

}