force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting Period</label>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Posting_Status__c.field-meta.xml
<CustomField>
    <fullName>Posting_Status__c</fullName>
    <defaultValue>&quot;Entered&quot;</defaultValue>
    <description>The posting status to the general ledger</description>
    <inlineHelpText>The posting status to the general ledger</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TA_AccPeriod_PostEntriesAU.cls
public with sharing class TA_AccPeriod_PostEntriesAU implements TriggerAction.AfterUpdate {

    @testVisible 
    private static final String STATUS_POSTED = 'Posted';
    @testVisible 
    private static final String STATUS_DENIED = 'Denied';

    public void afterUpdate(
        List<Accounting_Period__c> newList, List<Accounting_Period__c> oldList
    ) {
        // Identify newly posted accounting periods
        Map<Id, Accounting_Period__c> oldMap = new Map<Id, Accounting_Period__c>(oldList);
        Set<Id> setPeriodIds = new Set<Id>();
        for (Accounting_Period__c ap : newList) {
            if (
                ap.Status__c == STATUS_POSTED && 
                oldMap.get(ap.Id).Status__c != STATUS_POSTED
            ) {
                setPeriodIds.add(ap.Id);
            }
        }

        // Update jes for closed periods that have not been 'denied'
        List<Journal_Entry__c> lstEntriesToUpdate = new List<Journal_Entry__c>();
        lstEntriesToUpdate = [
            SELECT Id, Posting_Status__c 
              FROM Journal_Entry__c 
             WHERE Accounting_Period__c IN :setPeriodIds 
               AND Posting_Status__c != :STATUS_DENIED
             LIMIT 10000
        ];

        for (Journal_Entry__c je : lstEntriesToUpdate) {
            je.Posting_Status__c = STATUS_POSTED;
        }

        if (!lstEntriesToUpdate.isEmpty()) {
            try {
                update lstEntriesToUpdate;
            } catch (Exception e) {
                System.debug('::::: An exception occurred: ' + e.getMessage());
            }
        }

    }

}