force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/Journal_Entry__c.object-meta.xml
<CustomObject>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting Period</label>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Entry__c/fields/Posting_Status__c.field-meta.xml
<CustomField>
    <fullName>Posting_Status__c</fullName>
    <defaultValue>&quot;Entered&quot;</defaultValue>
    <description>The posting status to the general ledger</description>
    <inlineHelpText>The posting status to the general ledger</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TA_AccPeriod_HandleStatusChangeAU.cls
public with sharing class TA_AccPeriod_HandleStatusChangeAU implements TriggerAction.AfterUpdate {
    
    public void afterUpdate(
        List<Accounting_Period__c> newList, 
        List<Accounting_Period__c> oldList
    ) {
        // Identify accounting periods with changed statuses
        Map<Id, Accounting_Period__c> oldMap = new Map<Id, Accounting_Period__c>(oldList);
        Set<Id> setPeriodIds = new Set<Id>();
        for (Accounting_Period__c ap : newList) {
            if (
                ap.Status__c != oldMap.get(ap.Id).Status__c
            ) {
                setPeriodIds.add(ap.Id);
            }
        }

        // Get jes for identified accounting periods
        List<Journal_Entry__c> lstEntriesToUpdate = new List<Journal_Entry__c>();
        lstEntriesToUpdate = [
            SELECT Id, Posting_Status__c 
              FROM Journal_Entry__c 
             WHERE Accounting_Period__c IN :setPeriodIds 
               AND Posting_Status__c != :fsl_Constants.JE_STATUS_DENIED
             LIMIT 10000
        ];


        for (Journal_Entry__c je : lstEntriesToUpdate) {
            
        }



        /*
        @testVisible 
    static final String AP_STATUS_OPEN = 'Open';
    @testVisible 
    static final String AP_STATUS_CLOSED = 'Closed';
    @testVisible 
    static final String JE_STATUS_ENTERED = 'Entered';
    @testVisible 
    static final String JE_STATUS_POSTED = 'Posted';
    @testVisible 
    static final String JE_STATUS_DENIED = 'Denied';
    */

    }

}