force-app/main/default/objects/Future_Allocation__c/Future_Allocation__c.object-meta.xml
<CustomObject>
    <description>A scheduled allocation for a particular opportunity</description>
    <label>Future Allocation</label>
    <nameField>
        <displayFormat>F-ALL-{00000}</displayFormat>
        <label>Future Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Allocation__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of the opportunity to allocate to this general accounting unit. Leave blank for percent based allocations.</description>
    <inlineHelpText>Amount of the opportunity to allocate to this general accounting unit. Leave blank for percent based allocations.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Allocation__c/fields/Future_Allocation_Set__c.field-meta.xml
<CustomField>
    <fullName>Future_Allocation_Set__c</fullName>
    <label>Future Allocation Set</label>
    <referenceTo>Future_Allocation_Set__c</referenceTo>
    <relationshipLabel>Future Allocations</relationshipLabel>
    <relationshipName>Future_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Future_Allocation__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <description>Percent of opportunity amount to allocate to this general accounting unit. Modifying an opportunity amount of a percent based allocation will modify the allocation amount.</description>
    <inlineHelpText>Percent of opportunity amount to allocate to this general accounting unit. Modifying an opportunity amount of a percent based allocation will modify the allocation amount.</inlineHelpText>
    <label>Percent</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Future_Allocation_Set__c/Future_Allocation_Set__c.object-meta.xml
<CustomObject>
    <description>A grouping of allocations for a particular opportunity, representing a future revenue state</description>
    <label>Future Allocation Set</label>
    <nameField>
        <displayFormat>FAS-{00000}</displayFormat>
        <label>Future Allocation Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Allocation Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Allocation_Set__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Future Allocation Sets</relationshipLabel>
    <relationshipName>Future_Allocation_Sets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TA_FALL_QueriesBI.cls
public class TA_FALL_QueriesBI {

    private static TA_FALL_QueriesBI instance;

    private TA_FALL_QueriesBI() {}

    public static TA_FALL_QueriesBI getInstance() {
        if (TA_FALL_QueriesBI.instance == null) {
            TA_FALL_QueriesBI.instance = new TA_FALL_QueriesBI();
        }
        return TA_FALL_QueriesBI.instance;
    }

    public Map<Id, Future_Allocation_Set__c> mapSets { get; private set; }

    /*****************************************************
    * Called by metadata trigger handler
    * Manage from sObject Trigger Settings mdt: Future Allocation
    ******************************************************/

    public class Service implements TriggerAction.BeforeInsert {

        public void beforeInsert(List<Future_Allocation__c> newList) {
            TA_FALL_QueriesBI.getInstance().mapSets = getSetMap(newList);
        }

        private Map<Id, Future_Allocation_Set__c> getSetMap(
            List<Future_Allocation__c> newList
        ) {
            Set<Id> setFasIds = new Set<Id>();
            for (Future_Allocation__c fa : newList) setFasIds.add(fa.Future_Allocation_Set__c);
            Map<Id, Future_Allocation_Set__c> mapSets = new Map<Id, Future_Allocation_Set__c>([
                SELECT Id, Opportunity__c, Opportunity__r.Amount, 
                       (SELECT Id, Amount__c, Percent__c 
                          FROM Future_Allocations__r)
                  FROM Future_Allocation_Set__c
                 WHERE Id IN :setFasIds
            ]);
            return mapSets;
        }

    }

}