force-app/main/default/objects/Future_Allocation__c/Future_Allocation__c.object-meta.xml
<CustomObject>
    <description>A scheduled allocation for a particular opportunity</description>
    <label>Future Allocation</label>
    <nameField>
        <displayFormat>F-ALL-{00000}</displayFormat>
        <label>Future Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Allocation__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of the opportunity to allocate to this general accounting unit. Leave blank for percent based allocations.</description>
    <inlineHelpText>Amount of the opportunity to allocate to this general accounting unit. Leave blank for percent based allocations.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Allocation__c/fields/Future_Allocation_Set__c.field-meta.xml
<CustomField>
    <fullName>Future_Allocation_Set__c</fullName>
    <label>Future Allocation Set</label>
    <referenceTo>Future_Allocation_Set__c</referenceTo>
    <relationshipLabel>Future Allocations</relationshipLabel>
    <relationshipName>Future_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Future_Allocation_Set__c/Future_Allocation_Set__c.object-meta.xml
<CustomObject>
    <description>A grouping of allocations for a particular opportunity, representing a future revenue state</description>
    <label>Future Allocation Set</label>
    <nameField>
        <displayFormat>FAS-{00000}</displayFormat>
        <label>Future Allocation Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Allocation Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Allocation_Set__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Future Allocation Sets</relationshipLabel>
    <relationshipName>Future_Allocation_Sets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TA_FALL_ValidateAmountBI.cls
public with sharing class TA_FALL_ValidateAmountBI implements TriggerAction.BeforeInsert {

    private static Map<Id, Future_Allocation_Set__c> mapSets;

    public void beforeInsert(List<Future_Allocation__c> newList) {
        // Get sets with child records
        mapSets = TA_FALL_QueriesBI.getInstance().mapSets;

        // Group records in trigger by set
        Map<Id, List<Future_Allocation__c>> mapSetToTriggerFalls;
        mapSetToTriggerFalls = new Map<Id, List<Future_Allocation__c>>();
        for (Future_Allocation__c fall : newList) {
            if (!mapSetToTriggerFalls.containsKey(fall.Future_Allocation_Set__c)) {
                mapSetToTriggerFalls.put(
                    fall.Future_Allocation_Set__c, 
                    new List<Future_Allocation__c>()
                );
            }
            List<Future_Allocation__c> lstUpdatedFalls = mapSetToTriggerFalls.get(fall.Future_Allocation_Set__c);
            lstUpdatedFalls.add(fall);
            mapSetToTriggerFalls.put(
                fall.Future_Allocation_Set__c, 
                lstUpdatedFalls
            );
        }

        // Check that total value of each set does not exceed opp total
        for (Future_Allocation__c curfall : newList) {
            Decimal oppTotal = mapSets.get(curfall.Future_Allocation_Set__c)?.Opportunity__r.Amount;
            Decimal setTotal = 0;

            for (Future_Allocation__c tFall : mapSetToTriggerFalls.get(curfall.Future_Allocation_Set__c)) {
                setTotal += tFall.Amount__c != null ? tFall.Amount__c : 0;
            }
            for (Future_Allocation__c setFall : mapSets.get(curfall.Future_Allocation_Set__c).Future_Allocations__r) {
                setTotal += setFall.Amount__c;
            }

            if (setTotal > oppTotal) {
                String errorMessage = 'The amount allocated in the set must not exceed the opportunity amount of $' + oppTotal;
                curfall.addError(errorMessage);
            }
        }
        
    }

}